-- MySQL Script generated by MySQL Workbench
-- 03/19/15 18:18:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stablestudy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stablestudy` ;
-- -----------------------------------------------------
-- Schema stablestudy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stablestudy` ;
USE `stablestudy` ;

-- -----------------------------------------------------
-- Table `stablestudy`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stablestudy`.`users` ;
CREATE TABLE IF NOT EXISTS `stablestudy`.`users` (
  `fName` VARCHAR(20) NOT NULL,
  `lName` VARCHAR(20) NOT NULL,
  `school` VARCHAR(45) NOT NULL,
  `username` VARCHAR(20) NOT NULL UNIQUE,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stablestudy`.`rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stablestudy`.`rooms` ;
CREATE TABLE IF NOT EXISTS `stablestudy`.`rooms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `buildingName` VARCHAR(45) NOT NULL,
  `chairs` INT NULL,
  `computers` INT NULL,
  `whiteboards` INT NULL,
  `printers` INT NULL,
  `projectors` INT NULL,
  `restricted` TINYINT(1) NULL,
  `pictureurl` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stablestudy`.`buildings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stablestudy`.`buildings` ;
CREATE TABLE IF NOT EXISTS `stablestudy`.`buildings` (
  `buildingName` VARCHAR(100) NOT NULL,
  `closedAtNight` TINYINT(1) NULL,
  `onCampus` TINYINT(1) NULL,
  `address` VARCHAR(100) NULL,
  PRIMARY KEY (`buildingName`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
